# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
np.show_config()

2.0.1
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/kyeongmin kim/.conda/envs/numerics/Library/include
    lib directory: C:/Users/kyeongmin kim/.conda/envs/numerics/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_0123vcxhf8\croot\numpy_and_numpy_base_1725470331966\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/kyeongmin kim/.conda/envs/numerics/Library/include
    lib directory: C:/Users/kyeongmin kim/.conda/envs/numerics/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_0123vcxhf8\croot\numpy_and_numpy_base_1725470331966\_h_env\Library\lib\pkgconfig
    version: '2023.1'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version:

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
null_vector = np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [4]:
print('Memory size:', null_vector.nbytes)

Memory size: 80


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [5]:
vector1 = np.zeros(10)
vector1[4] = 1
print(vector1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [6]:
vector2 = np.arange(10,50)
print(vector2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [7]:
vector3 = vector2[::-1]
print(vector3)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
vector4 = np.arange(9)
vector5 = vector4.reshape(3,3)
print(vector5)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [14]:
array1 = np.array([1,2,0,0,4,0])
indices = np.nonzero(array1)
print('indices of non-zero elements:', indices[0])

indices of non-zero elements: [0 1 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [17]:
I1 = np.identity(3)
print(I1,'\n')

I2 = np.eye(3)
print(I2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [18]:
array1 = np.random.random((3,3,3))
print(array1)

[[[0.42980885 0.23669966 0.86629974]
  [0.65185396 0.47049498 0.69214005]
  [0.25581451 0.28969429 0.12008695]]

 [[0.97313071 0.19453916 0.99023257]
  [0.65819799 0.28406108 0.38911148]
  [0.16288398 0.51652635 0.62863936]]

 [[0.14000514 0.48280058 0.00842736]
  [0.82039083 0.03172584 0.47790456]
  [0.28990138 0.32541701 0.81165996]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [21]:
array2 = np.random.random((10,10))
min_val = array2.min()
max_val = array2.max()

print('Min value :', min_val)
print('Max value :', max_val)

Min value : 0.006121160769999023
Max value : 0.9972532168965824


#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [22]:
vector6 = np.random.random(30)
mean_val = vector6.mean()

print('Mean value :', mean_val)

Mean value : 0.5440043291969359


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [23]:
array3 = np.ones((6,6))
array3[1:-1, 1:-1] = 0

print(array3)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan, False, False, nan, True, True

In [ ]:
nan, False, False, nan, True, False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [24]:
vector7 = np.array([1,2,3,4])
array4 = np.zeros((5,5))
array4[np.arange(1,5), np.arange(0,4)] = vector7
print(array4)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [26]:
array5 = np.zeros((8,8), dtype=int)
array5[1::2, ::2] = 1
array5[::2, 1::2] = 1
print(array5)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [27]:
array6 = (6,7,8)
index = np.unravel_index(99, array6)

print(index)

(np.int64(1), np.int64(5), np.int64(3))


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [28]:
X = np.random.random((5,5))

mean = X.mean()
std = X.std()

Z = (X - mean) / std

print("Normalized matrix:\n", Z)

Normalized matrix:
 [[ 0.8841908  -1.94461703  0.10453231  0.18864639  0.29843785]
 [ 0.93333527  0.71113093  0.54707434  0.47333324 -1.67458366]
 [ 1.14571827 -1.57612595 -0.52934746  0.97852911 -0.80441439]
 [ 0.24547156  0.52164792 -1.28696536  0.42291537  1.20910796]
 [-0.04353629 -1.08417978  0.8898038   1.13202645 -1.74213166]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [31]:
color_dtype = np.dtype([
    ('R', np.ubyte),
    ('G', np.ubyte),
    ('B', np.ubyte),
    ('A', np.ubyte)
])

pixel = np.array([(10,20,30,40)], dtype = color_dtype)
print(pixel)
print(pixel['R'], pixel['G'], pixel['B'], pixel['A'])

[(10, 20, 30, 40)]
[10] [20] [30] [40]


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [32]:
A = np.random.random((5,3))
B = np.random.random((3,2))
C = A@B

print("Matrix C:\n", C)

Matrix C:
 [[0.49776119 0.72067347]
 [0.23120534 0.35535347]
 [0.65714229 0.36424858]
 [0.34231852 0.43481212]
 [0.60847126 0.26648727]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
array7 = np.random.randint(0,10,size=10)
print(array7)

array7[(array7>=3)&(array7<=8)] *= -1
print(array7)

[4 2 0 8 7 2 3 0 1 7]
[-4  2  0 -8 -7  2 -3  0  1 -7]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

*   Python Built-in sum Function: The sum of range(5) (which is 0 + 1 + 2 + 3 + 4 = 10) is computed, and then -1 is added to it. The result will be 9
*   NumPy's sum Function: NumPy's sum function doesn't treat the second argument as a start value like Python's built-in sum. Instead, it treats it as an axis parameter. Since -1 is not a valid axis for a 1D sequence (the valid axis for a 1D array is 0), NumPy will raise a TypeError


In [ ]:
9
TypeError

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 32. Create a random vector of size 10 and sort it (★★☆)

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
# column 3

In [ ]:
# column 2


In [ ]:
# column 3
