# 추천 시스템
## 추천 시스템의 개요와 배경
### **추천 시스템의 개요**
지금은 추천시스템의 전성시대. 전자상거래, 콘텐츠 포털 등 추천 시스템을 통해 사용자의 취향을 이해하고 맞춤 상품과 콘텐츠를 제공해 조금이라도 오래 자기 사이트에 고객을 머무리게 하기 위해 노력하고 있음.

하나의 콘텐츠를 선택했을 때 선택된 콘텐츠와 연관된 추천 콘텐츠가 얼마나 사용자의 관심을 끌고 개인에게 맞춘 콘텐츠를 추천했는지는 그 사이트의 평판을 좌우하는 매우 중요한 요소.

**추천 시스템의 진정한 묘미**: 사용자 자신도 좋아하는지 몰랐던 취향을 시스템이 발견하고 그에 맞는 콘텐츠를 추천해주는 것. ->  이러한 추천 시스템을 접한 사용자는 해당 사이트를 더 강하게 신뢰하게 되어 더 많은 추천 콘텐츠를 선택하게 됨. ->  결국 더 많은 데이터가 추천 시스템에 축적되면서 추천이 더욱 정확해지고 다양한 결과를 얻을 수 있는 좋은 선순환 시스템을 구축.

### **온라인 스토어의 필수 요소, 추천 시스템**
추천 시스템은 특히 온라인에서 그 진가를 발휘. 한정된 시간이라는 제약을 가진 상황에서 너무 많은 상품과 콘텐츠는 오히려 사용자가 어떤 상품을 골라야 할지에 대한 압박감을 느끼게 만들 수밖에 없는데, 추천 시스템이 이러한 상황을 타개해줌. 좋은 추천 시스템은 사용자가 무엇을 원하는지 빠르게 찾아내 사용자의 온라인 쇼핑의 즐거움을 배가 함.
* 추천 시스템 구성 요소 예시
  * 사용자가 어떤 상품을 구매했는가?
  * 사용자가 어떤 상품을 둘러보거나 장바구니에 넣었는가?
  * 사용자가 평가한 영화 평점은? 제품 평가는?
  * 사용자가 스스로 작성한 자신의 취향은?
  * 사용자가 무엇을 클릭했는가?

### **추천 시스템의 유형**
* **콘텐츠 기반 필터링(Content based filtering) 방식**
* **협업 필터링(Collaborative Filtering) 방식**
  * 최근접 이웃(Nearest Neighbor) 협업 필터링
  * 잠재 요인(Latent Factor) 협업 필터링

추천 시스템의 초창기에는 콘텐츠 기반 필터링이나 최근접 이웃 기반 협업 필터링이 주로 사용됐지만, 그 유명한 넷플릭스 추천 시스템 경연 대회에서 행렬 분해(Matrix Factorization) 기법을 이용한 잠재 요인 협업 필터링 방식이 우승하면서 대부분의 온라인 스토어에서 잠재 요인 협업 필터링 기반의 추천 시스템을 적용하고 있음.

하지만 서비스하는 아이템의 특성에 따라 콘텐츠 기반 필터링이나 최근접 이웃 기반 협업 필터링 방식을 유지하는 사이트도 많으며, 특히 아마존의 경우는 아직도 아이템 기반의 최근접 이웃 협업 필터링 방식을 추천 엔진으로 사용.

요즘에는 개인화 특성을 좀 더 강화하기 위해서 하이브리드 형식으로 콘텐츠 기반과 협업 기반을 적절히 결합해 사용하는 경우도 늘고 있음.

## **콘텐츠 기반 필터링 추천 시스템**
콘텐츠 기반 필터링 방식은 사용자가 특정한 아이템을 매우 선호하는 경우, 그 아이템과 비슷한 콘텐츠를 가진 다른 아이템을 추천하는 방식. e.g.영화 평점, 장르, 출연 배우 등

## **최근접 이웃 협업 필터링**
친구들에게 물어보는 것과 유사한 방식으로, 사용자가 아이템에 매긴 평점 정보나 상품 구매 이력과 같은 사용자 행동 양식(User Behavior)만을 기반으로 추천을 수행하는 것이 협업 필터링(Collaborative Filtering) 방식.

협업 필터링의 주요 목표는 사용자-아이템 평점 매트릭스와 같은 축적된 사용자가 행동 데이터를 기반으로 사용자가 아직 평가하지 않은 아이템을 예측 평가하는 것.

협 업 필터링 기반의 추천 시스템은 최근접 이웃 방식과 잠재 요인 방식으로 나뉘며, 두 방식 모두 사용자-아이템 평점 행렬 데이터에만 의지해 추천을 수행.
- 협업 필터링 알고리즘에 사용되는 사용지-아이템 평점 행렬에서 행(Row)은 개별 사용자, 열(Column)은 개별 아이템으로 구성되며, 사용자 아이디 행, 아이템 아이디 열 위치에 해당하는 값이 평점을 나타내는 형태가 돼야 함.
- 일반적으로 이러한 사용자-아이템 평점 행렬은 많은 아이템을 일로 가지는 다차원 행렬. 사용자가 아이템에 대한 평점을 매기는 경우가 많지 않기 때문에 희소 행렬(Sparse Matrix) 특성을 가짐.
- 최근접 이웃 협업 필터링은 메모리(Memory) 협업 필터링이라고도 하며, 일반적으로 사용자 기반과 아이템 기반으로 다시 나뉠 수 있음.
  - 사용자 기반(User—User)： 당신과 비슷한 고객들이 다음 상품도 구매했습니다.
    -  특정 사용자와 유사한 다른 사용자를 Top-N으로 선정해 이 Top-N 사용자가 좋아하는 아이템을 추천하는 방식.
  - 아이템 기반(Item네em)： 이 상품을 선택한 다른 고객들은 다음 상품도 구매했습니다.
    - 아이템 기반 최근접 이웃 방식은 아이템이 가지는 속성과는 상관없이 사용자들이 그 아이템을 좋아하는지/싫어하는지의 평가 척도가 유사한 아이템을 추천하는 기준이 되는 알고리즘.
  - 일반적으로 사용자 기반보다는 아이템 기반 협업 필터링이 정확도가 더 높음.
  


## **잠재 요인 협업 필터링**
### **잠재 요인 협업 필터링의 이해**
잠재 요인 협업 필터링은 사용자-아이템 평점 매트릭스 속에 숨어 있는 잠재 요인을 추출해 추천 예측을 할 수 있게 하는 기법.

대규모 다차원 행렬을 SVD와 같은 차워 감소 기법으로 분해하는 과정에서 잠재 요인을 추출하는데, 이러한 기법을 행렬 분해(Matrix Factorization).

잠재 요인 협업 필터링은 사용자-아이템 평점 행렬 데이터만을 이용해 말 그대로 ‘잠재 요인’을 끄집어내는 것을 의미.

* 잠재 요인을 기반으로  다차원 희소 행렬인 사용자一아이템 행렬 데이터를 저차원 밀집 행렬의 사용자-잠재 요인 행렬과 아이템-잠재 요인 행렬의 전치 행렬（즉, 잠재 요인-아이템 행렬）로 분해할 수 있으며, 이렇게 분해된 두 행렬의 내적을 통해 새로운 예측 사용자—아이템 평점 행렬 데이터를 만들어서 사용자가 아직 평점을 부여하지 않는 아이템에 대한 예측 평점을 생성하는 것이 잠재 요인 협력 필터링 알고리즘의 골자.
* 행렬 분해에 의해 추출되는 ‘잠재 요인’이 정확히 어떤 것인지는 알 수 없지만, 가령 영화 평점 기반의
사용자-아이템 평점 행렬 데이터라면 영화가 가지는 장르별 특성 선호도로 가정할 수 있음.
* 평점이란 사용자의 특정 영화 장르에 대한 선호도와 개별 영화의 그 장르적 특성값을 반영해 결정된다고 생각할 수 있음.
* 이처럼 잠재 요인 협업 필터링은 숨겨져 있는 ‘잠재 요인’을 기반으로 분해된 매트릭스를 이용해 사용자가 아직 평가하지 않은 아이템에 대한 예측 평가를 수행하는 것.

### **행렬 분해의 이해**
행렬 분해는 다차워의 매트릭스를 저차원 매트릭스로 분해하는 기법으로서 대표적으로 SVD（Singular Vector Decomposition）, NMF（Non—Negative Matrix Factorization） 등이 있음

M개의 사용자（User） 행과 N개의 아이템（item） 열을 가진 평점 행렬 R은 M X N 차원으로 구성되며, 행렬 분해를 통해서 사용자-K 차원 잠재 요인 행렬 P（P 는 MXK 차원）와 K 차원 잠재 요인 - 아이템 행렬 Q.T（Q.T 는 KXN 차원）로 분해될 수 있음.

**R = P*Q.T**
* M은 총 사용자 수
* N은 총 아이템 수
* K는 잠재 요인의 차원 수
* R은 MXN 차원의 사용자-아이템 평점 행렬
* P 는 사용자와 잠재 요인과의 관계 값을 가자는 MXK 차원의 사용자-잠재 요인 행렬
* Q 는 아이템과 잠재 요인과의 관계 값을 가지는 NXK 차원의 아이템-잠재 요인 행렬
* Q.T는 Q 매트릭스의 행과 열 값을 교환한 전치 행렬

### **확률적 경사 하강법을 이용한 행렬 분해**
확률적 경사 하강법을 이용한 행렬 분해 방법을 요약하자면, P와 Q 행렬로 계산된 예측 R 행렬 값이 실제 R 행렬 값과 가장 최소의 오류를 가질 수 있도록 반복적인 비용 함수 최적화를 통해 P와 아를 유추해내는 것.

절차
1. P와 Q를 임의의 값을 가진 행렬로 설정.
2. P와 Q.T 값을 곱해 예측 R 행렬을 계산하고 예측 R 행렬과 실제 R 행렬에 해당하는 오류 값을 계산.
3. 이 오류 값을 최소화할 수 있도록 P와 Q 행렬을 적절한 값으로 각각 업데이트.
4. 만족할 만한 오류 값을 가질 때까지 2, 3번 작업을 반복하면서 P와 Q 값을 업데이트해 근사화.

In [ ]:
import numpy as np

# 원본 행렬 R 생성, 분해 행렬 P와 Q 초기화, 잠재 요인 차원 K는 3으로 설정.
R = np.array([[4, np.nan, np.nan, 2, np.nan],
              [np.nan, 5, np.nan, 3, 1],
              [np.nan, np.nan, 3, 4, 4],
              [5, 2, 1, 2, np.nan]])
num_users, num_items = R.shape
K=3

# P와 Q 행렬의 크기를 지정하고 정규 분포를 가진 임의의 값으로 입력합니다.
np.random.seed(1)
P = np.random.normal(scale=1./K, size=(num_users, K))
Q = np.random.normal(scale=1./K, size=(num_items, K))

In [ ]:
from sklearn.metrics import mean_squared_error

def get_rmse(R, P, Q, non_zeros):
  error=0
  # 두 개의 분해된 행렬 P와 Q.T의 내적으로 예측 R 행렬 생성
  full_pred_matrix = np.dot(P, Q.T)

  # 실제 R 행렬에서 널이 아닌 값의 위치 인덱스 추출해 실제 R 행렬과 예측 행렬의 RMSE 추출
  x_non_zero_ind = [non_zero[0] for non_zero in non_zeros]
  y_non_zero_ind = [non_zero[1] for non_zero in non_zeros]
  R_non_zeros = R[x_non_zero_ind, y_non_zero_ind]
  full_pred_matrix_non_zeros = full_pred_matrix[x_non_zero_ind, y_non_zero_ind]
  mse = mean_squared_error(R_non_zeros, full_pred_matrix_non_zeros)
  rmse = np.sqrt(mse)

  return rmse

In [ ]:
# R > 0인 행 위치, 열 위치, 값을 non_zeros 리스트에 저장.
non_zeros = [ (i, j, R[i, j]) for i in range(num_users) for j in range(num_items) if R[i, j] > 0 ]

steps=1000
learning_rate=0.01
r_lambda=0.01

# SGD 기법으로 우와 Q 매트릭스를 계속 업데이트.
for step in range(steps):
  for i, j, r in non_zeros:
    # 실제 값과 예측 값의 차이인 오류 값 구함
    eij = r - np.dot(P[i, :], Q[j, :].T)
    # Regularization을 반영한 SGD 업데이트 공식 적용
    P[i, :] = P[i, :] + learning_rate * (eij * Q[j, :] - r_lambda * P[i, :])
    Q[j, :] = Q[j, :] + learning_rate * (eij * P[i, :] - r_lambda * Q[j, :])

    rmse = get_rmse(R, P, Q, non_zeros)
    if (step % 50) == 0 :
      print("### iteration step : ", step, " rmse : ", rmse)

### iteration step :  0  rmse :  3.228772440179629
### iteration step :  0  rmse :  3.227192934527693
### iteration step :  0  rmse :  3.2177713822637233
### iteration step :  0  rmse :  3.214302364096318
### iteration step :  0  rmse :  3.2143149047384463
### iteration step :  0  rmse :  3.212931049767472
### iteration step :  0  rmse :  3.210673020185091
### iteration step :  0  rmse :  3.2087997955883325
### iteration step :  0  rmse :  3.2009798396670117
### iteration step :  0  rmse :  3.1975184708378572
### iteration step :  0  rmse :  3.1974675839584537
### iteration step :  0  rmse :  3.1949134908615826
### iteration step :  50  rmse :  0.4540951335595225
### iteration step :  50  rmse :  0.4534019372307101
### iteration step :  50  rmse :  0.4501882085472817
### iteration step :  50  rmse :  0.45015164155052023
### iteration step :  50  rmse :  0.4498766681518435
### iteration step :  50  rmse :  0.44903882020656366
### iteration step :  50  rmse :  0.44868002239945665
### ite

In [ ]:
pred_matrix = np.dot(P, Q.T)
print('예측 행렬:\n', np.round(pred_matrix, 3))

예측 행렬:
 [[3.994 1.237 1.326 1.996 1.758]
 [7.509 4.975 1.185 2.984 1.004]
 [6.992 1.703 2.987 3.977 3.985]
 [4.964 2.013 1.006 2.02  1.3  ]]
