# 인공지능, 머신 러닝과 딥러닝
인공지능 > 머신 러닝 > 답러닝

* AI: 인간의 지능을 모방하여 사람이 하는 일을 컴퓨터(기계)가 할 수 있도록 하는 기술.
  * 머신러닝: 주어진 데이터를 인간이 먼저 처리(전처리). 범용적인 목적을 위해 제작된 것으로 데이터의 특징을 스스로 추출하지 못함. 학습 과정은 각 데이터(혹은 이미지) 특성을 컴퓨터(기계)에 인식시키고 학습시켜 문제를 해결.
    * 딥러닝: 인간이 하던 작업을 생략. 대량의 데이터를 신경망에 적용하면 컴퓨터가 스스로 분석한 후 답을 찾음.
---
### **머신 러닝**
머신 러닝은 인공지능의 한 분야로， 컴퓨터 스스로 대용량 데이터에서 지식이나 패턴을 찾아 학습하고 예측을 수행하는 것.

크게 학습 단계와 예측 단계로 나뉨.

*특성추출: 머신 러닝에서 컴퓨터가 스스로 학습하려면 즉 컴퓨터가 입력받은 데이터를 분석하여 일정한 때턴이나 규칙을 찾아내려면 사람이 인지하는 데이터를 컴퓨터가 인지할 수 있는 데이터로 변환해 주어야 함. 이때 데이터별로 어떤 특
징을 가지고 있는지 찾아내고, 그것을 토대로 데이터를 벡터로 변환하는 작업을 특성 추출이라고 함.

머신 러닝의 주요 구성 요소
* 데이터:  머신 러닝이 학습 모델을 만드는 데 사용하는 것.
* 모델:  머신 러닝의 학습 단계에서 얻은 최종 결과물로 가설

*수집된 데이터셋은 크게 훈련(training)과 테스트(test) 데이터셋으로 분리하여 사용!

머신러닝 학습 알고리즘
* 지도 학습:  정답이 무엇인지 컴퓨터에 알려 주고 학습시키는 방법.
* 비지도 학습:  정답을 알려 주지 않고 특정이 비슷한 데이터를 클러스터링하여 예측하는 학습 방법.
* 강화학습: 분류할 수 있는 데이터가 있는 것도 아니고 데이터가 있다고 해도 정답이 X. 자신의 행동에 대한 보상을 받으며 학습.

---
### **딥러닝**
인간의 신경망 원리를 모방한 심층 신경망 이론을 기반으로 고안된 머신 러닝 방법의 일종. 심층 신경망(DNN) 사용.

인간의 뇌가 엄청난 수의 뉴런(m:uron)과 시법스(synapsc)로 구성되어 있는 것에 착안하여 검퓨터에 뉴럽과 시냅스 개념을 적용.

딥러닝 학습 과정
1. 데이터 준비: 파이토치에서 제공 하는 데이터셋 사용 or 캐글
2. 모델 정의: 신경망 생성. 은닉층 개수 많을수록 성능 굿. but 과적합 가능성 높.
3. 모델 컴파일: 컴파일 단계에서 활성화 함수, 손실 함수, 옵티마이저를 선택.
    * 훈련 데이터셋 형태가 연속형이면 MSE, 이진분류면 크로스 엔트로피 선택.
4. 모델 훈련: 훈련 단계에서는 한 번에 처리할 데이터양을 지정. 전체 훈련 데이터셋에서 일정한 묶음으로 나누어 처리할 수 있는 배치와 훈련의 횟수인 에포크 선택이 중요.
    * E.G. 훈련 데이터셋 1000개에 대한 배츠 크기가 20 = 샘플 단위 20개마다 모델 가중치를 한 번씩 업데이트시킨다는 의미. 즉, 총 50번의 가중치 업데이터. 결과적으로 가중치가 총 500번 업데이트.
5. 모델 예측: 검증 데이터셋을 생성한 모텔(모형)에 적용하여 실제로 예측을 진행.

딥러닝 학습 과정에서 중요한 핵심 구성 요소: 신경망, 역전파

딥러닝 알고리즘
* 지도 학습: CNN, RNN, LSTM
* 비지도 학습: 워드 임베딩, 군집
  * 군집: 아무런 정보가 없는 상태에서 데이터를 분류하는 방법.
* 전이 학습:  사전에 학습이 완료된 모댈(pre-trained model)(사전 학습 모댈)을 가지고우리가원하는학습에 미세 조정 기법 이용하여 학습시키는 방법.
  * 사전 학습 모델: 풀고자 하는 문제와 비슷하면서 많은 데이터로 이미 학습이 되어 있는 모댈.


# 파이토치
파이토치는 2017년 초에 공개된 답러닝 프레임워크로 루아(L떠) 언어로 개발되었던 토치(Torch)를 페이스북에서 파이씬 버전으로 내놓은 것.

대상
* 넘파이를 대체하면서 GPU를 이용한 연산이 필요한 경우
* 최대한의 유연성과속도를제공하는답러닝 연구플랫폼이 필요한 경우

### **파이토치 특징 및 장점**
GPU에서 텐서 조작 및 동적 신경망 구축이 가능한 프레임워크
* GPU: 연산 속도 빠르게 함. 내부적으로 CUDA, cuDNN API퉁홰 연산.
* 텐서: 파이토치의 데이터 형태, 단일 데이터 형식으로 된 자료들의 다차원 행렬.
* 동적 신경망: 훈련을 반복할 때마다 네트워크 변경이 가능한 신경망을 의미.

장점
* 단순함
* 성능 굿
* 직관적인 인터페이스

### ** 파이토치의 아키텍처**
크게 세 개의 계층. 가장 상위에 파이토치API, 그 아래에 파이토치 엔진, 마지막 아래에 텐서에 대한 연산 처리.
* 파이토치 API
  * torch: GPU를 지원하는 텐서 패키지
  * torch.autograd: 자동 미분 패키지
  * torch.nn: 신경망 구축 및 훈련 패키지
  * torch.multiprocessing: 파이씬 멀티프로세싱 패키지
  * torch.utils: DataLoader 및 기타 유틸리티를 제공하는 패키지

* 파이토치 엔진: Autograd C++, Aten C++, JIT C+十， Python API로 구성
* 연산 처리: 가장 아래 계층에 속하는 C 또는 CUDA 패키지는 상위의 API에서 할당된 거의 모든 계산을 수행.

## **파이토치 기초문법**

텐서생성및변환

In [1]:
import torch
print(torch.tensor([[1,2],[3,4]]))
print(torch.tensor([[1,2],[3,4]], device = 'cuda:0'))
print(torch.tensor([[1,2],[3,4]], dtype=torch.float64))

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], device='cuda:0')
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [4]:
temp = torch.tensor([[1,2],[3,4]])
print(temp.numpy())

temp = torch.tensor([[1,2],[3,4]], device = 'cuda:0')
print(temp.to('cpu').numpy())

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


텐서의인텍스조작

In [5]:
temp = torch.FloatTensor([1,2,3,4,5,6,7])
print(temp[0],temp[1], temp[-1])
print(temp[2:5], temp[4:-1])

tensor(1.) tensor(2.) tensor(7.)
tensor([3., 4., 5.]) tensor([5., 6.])


텐서언산및차원조작

In [6]:
v = torch. tensor( [1 , 2, 3]) # 길이가 3인 벡터 생성
w = torch.tensor([3, 4, 6])
print (w - v) # 길이가 같은 벡터 간 뺄셈 연산

tensor([2, 2, 3])


In [7]:
temp = torch.tensor([
[1 , 2], [3, 4]]) # 2x2 행렬생성
print(temp.shape)
print ('------------------------')
print( temp. view(4, 1)) # 2x2 행렬을 4x1로변형
print('------------------------')
print( temp. view( -1)) # 2x2 행렬을 1차원 벡터로 변형
print('------------------------') #-1은 (1, ?)와 같은 의미로 다른 차원으로부터 해당 값을 유추하겠다는
print( temp . view( 1, - 1) )
print('------------------------')
print (temp . view ( - 1, 1))

torch.Size([2, 2])
------------------------
tensor([[1],
        [2],
        [3],
        [4]])
------------------------
tensor([1, 2, 3, 4])
------------------------
tensor([[1, 2, 3, 4]])
------------------------
tensor([[1],
        [2],
        [3],
        [4]])


데이터준비

In [ ]:
import pandas as pd # pandas 라이브러리 호출
import torch # torch 라이브러리 호출

data = pd.read_csv('../class2.csv') # csv 파일을 불러옵니다.

x = torch.from_numpy(data['x'].values).unsqueeze(dim=1).float()
y = torch.from_numpy(data['y'].values).unsqueeze(dim=1).float()

In [ ]:
import pandas as pd
import torch
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

class CustomDataset(Dataset):
    def __init__(self, csv_file):
        # csv_file 파라미터를 통해 데이터셋을 불러옵니다.
        self.label = pd.read_csv(csv_file)

    def __len__(self):
        return len(self.label)

    def __getitem__(self, idx):
        # 전체 x와 y 데이터 중에 해당 idx번째의 데이터를 가져옵니다.
        sample = torch.tensor(self.label.iloc[idx, 0:3]).int()
        label = torch.tensor(self.label.iloc[idx, 3]).int()
        return sample, label

# 데이터셋으로 covtype.csv를 사용합니다.
tensor_dataset = CustomDataset('../covtype.csv')

# 데이터셋을 torch.utils.data.DataLoader에 파라미터로 전달합니다.
dataset = DataLoader(tensor_dataset, batch_size=4, shuffle=True)

파이토치에서 제공하는 데이터셋 사용

In [ ]:
import torchvision.transforms as transforms

# 평균이 0.5, 표준편차가 1.0이 되도록 데이터의 분포(normalize)를 조정
mnist_transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (1.0,))
])

from torchvision.datasets import MNIST
import requests

download_root = '../chap02/data/MNIST_DATASET' # 내려받을 경로 지정

# 훈련(training) 데이터셋
train_dataset = MNIST(download_root, transform=mnist_transform, train=True, download=True)

# 검증(validation) 데이터셋
valid_dataset = MNIST(download_root, transform=mnist_transform, train=False, download=True)

# 테스트(test) 데이터셋
test_dataset = MNIST(download_root, transform=mnist_transform, train=False, download=True)

단순 신경망을 정의하는 방법

In [ ]:
model = nn.Linear(in_features=1 , out_features=1 , bias=True)

nn.Module( )을 상속하여 정으|하는 방법

In [ ]:
import torch.nn as nn

class MLP(nn.Module):
    def __init__(self, inputs):
        super(MLP, self). __init__()
        self.layer = nn.Linear(inputs, 1) # 계층 정의
        self.activation = nn.Sigmoid() # 활성화 함수 정의

    def forward(self, X):
        X = self.layer(X)
        X = self.activation(X)
        return X

Sequential 신경망을 정의하는 방법

In [8]:
import torch.nn as nn

class MLP(nn.Module):
    def __init__(self):
        super(MLP, self).__init__()
        self.layer1 = nn.Sequential(
            nn.Conv2d(in_channels=3, out_channels=64, kernel_size=5),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2))

        self.layer2 = nn.Sequential(
            nn.Conv2d(in_channels=64, out_channels=30, kernel_size=5),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2))

        self.layer3 = nn.Sequential(
            nn.Linear(in_features=30*5*5, out_features=10, bias=True),
            nn.ReLU(inplace=True))

    def forward(self, x):
        x = self.layer1(x)
        x = self.layer2(x)
        x = x.view(x.shape[0], -1)
        x = self.layer3(x)
        return x

model = MLP() # 모델에 대한 객체 생성

print("Printing children\n-----------------------------------------")
print(list(model.children()))

print("\n\nPrinting Modules\n-----------------------------------------")
print(list(model.modules()))

Printing children
-----------------------------------------
[Sequential(
  (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU(inplace=True)
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
), Sequential(
  (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU(inplace=True)
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
), Sequential(
  (0): Linear(in_features=750, out_features=10, bias=True)
  (1): ReLU(inplace=True)
)]


Printing Modules
-----------------------------------------
[MLP(
  (layer1): Sequential(
    (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer3): Sequ

함수로 신경망을 정의하는 방법

## **모델의 파라미터 정의**
* 손실 함수: 학습하는 동안 출력과 실제 값(정답) 사이의 오차를 측정.
  * BCELoss: 이진 분류르 위해 사용.
  * CrossEntropyLoss: 다중 클래스 분류를 위해 사용.
  * MSELoss: 회귀 모텔에서 사용.
* 옵티마이저: 데이터와 손실 함수를 바탕으로 모델의 업데이트 방법을 결정.
  * optimizer는 step() 메서드를 통해 전달받은 파라미터를 업데이트.
  * 모델의 파라미터별로 다른 기준을 적용시킬 수 있음.
  * torch.optim.Optimizer(params, defaults)는 모든 옵티마이저의 기본이 되는 클래스.
  * zero_grad ( ) 메서드는 옵티마이저에 사용된 파라미터들의 기울기(gradient)를 0으로 만듦.
  * torch. optim.lr_scheduler는 에포크에 따라 학습률을 조절.
* 학습률 스케줄러: 미리 지정한 횟수의 에포크를 지날 때마다 학습률을 감소시킴.
  * optim.lr_scheduler. LambdaLR: 람다 함수를 이용하여 그 함수의 결괴를 학습률로 설정.
  * optim.lr_scheduler. StepLR: 특정 단계(step)마다 학습률을 감마(gamma) 비율만큼 감소.
  * optim.lr_scheduler. MultiStepLR: StepLR과 비슷하지만 특정 단계가 아닌 지정된 에포크에만 감마 비유롤 감소시킴.
  * optim.lr_scheduler.ExponentialLR: 에포크마다 이전 학습률에 감마만큼 곱함.
  * optim.lr_scheduler.CosineAnnealingLR: 학습률을 코사인 함수의 형태처럼 변화시킴.
  * optim.lr_scheduler.ReduceLROnPlateau: 학습이 잘되고 있는지 아닌지에 따라 동적으로 학습률을 변화시킬 수 있음.
* 지표: 훈련과 테스트 단계를 모니터링.

In [8]:
from torch.optim import optimizer

# 손실 함수 및 최적화 설정
criterion = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01, momentum=0.9)
scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer=optimizer,
                                              lr_lambda=lambda epoch: 0.95 ** epoch)

# 학습 루프
for epoch in range(1, 100+1): # 에포크 수만큼 데이터를 반복하여 처리
    for x, y in dataloader: # 배치 크기만큼 데이터를 가져와서 학습 진행
        optimizer.zero_grad()
        # 이미지에는 loss_fn으로 되어 있으나 위에서 정의한 criterion을 사용하는 것이 일반적입니다.
        loss = criterion(model(x), y)
        loss.backward()
        optimizer.step()
    scheduler.step()

## 모델훈련
앞서 만들어 둔 데이터로 모델을 학습. 이때 학습을 시킨다는 것은y = wx + b라는 함수에서 W와b의 적절한값을찾는다는 의미.

w와b에 임의의 값을적용하여 시작하며 오차가 줄어들어 전역 최소점에 이를 때까지 파라미터(w, b)를 계속 수정.

가장 먼저 필요한 절차가 optimizer.zero_9rad() 메서드를 이용하여 기울기를 초기화하는 것.

In [ ]:
for epoch in range(100):
    yhat = model(x_train)
    loss = criterion(yhat, y_train)

    optimizer.zero_grad() # 오차가 중첩적으로 쌓이지 않도록 초기화
    loss.backward()
    optimizer.step()

모델평가

In [9]:
! pip install torchmetrics

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 25.6 MB/s eta 0:00:00


In [12]:
import torch
import torchmetrics

# 예측값 (10개의 샘플, 5개 클래스 확률)
preds = torch.randn(10, 5).softmax(dim=-1)
# 실제 정답 (0~4 사이의 정수 10개)
target = torch.randint(5, (10,))

# 최신 버전에서는 task와 num_classes를 반드시 지정해야 합니다.
acc = torchmetrics.functional.accuracy(preds, target, task="multiclass", num_classes=5)

print(f"Single Batch Accuracy: {acc}")

Single Batch Accuracy: 0.0


In [13]:
import torch
import torchmetrics

# 모델 평가(정확도) 객체 초기화
metric = torchmetrics.Accuracy(task="multiclass", num_classes=5)

n_batches = 10
for i in range(n_batches):
    # 매 배치마다 가상의 예측값과 정답 생성
    preds = torch.randn(10, 5).softmax(dim=-1)
    target = torch.randint(5, (10,))

    # 현재 배치에 대한 정확도 계산 및 내부 상태 업데이트(데이터 누적)
    acc = metric(preds, target)
    print(f"Accuracy on batch {i}: {acc}")

# 모든 배치(10개)의 데이터를 합산하여 전체 데이터에 대한 최종 정확도 계산
total_acc = metric.compute()
print(f"\nAccuracy on all data: {total_acc}")

Accuracy on batch 0: 0.0
Accuracy on batch 1: 0.10000000149011612
Accuracy on batch 2: 0.20000000298023224
Accuracy on batch 3: 0.20000000298023224
Accuracy on batch 4: 0.20000000298023224
Accuracy on batch 5: 0.30000001192092896
Accuracy on batch 6: 0.5
Accuracy on batch 7: 0.20000000298023224
Accuracy on batch 8: 0.20000000298023224
Accuracy on batch 9: 0.0

Accuracy on all data: 0.1899999976158142


훈련 과정 모니터링

In [14]:
! pip install tensorboard

In [ ]:
import torch
from torch.utils.tensorboard import SummaryWriter

# 모니터링에 필요한 값들이 저장될 위치
writer = SummaryWriter("../chap02/tensorboard")

for epoch in range(num_epochs):
    model.train() # 학습 모드로 전환(dropout=True)
    batch_loss = 0.0

    for i, (x, y) in enumerate(dataloader):
        x, y = x.to(device).float(), y.to(device).float()
        outputs = model(x)
        loss = criterion(outputs, y)

        # 스칼라 값(오차)을 기록
        writer.add_scalar("Loss", loss, epoch)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

# SummaryWriter가 더 이상 필요하지 않으면 close() 메서드 호출
writer.close()

In [ ]:
! tensorboard --logdir= .. /chap02/tensorboard --port=6006

* model. train(): 훈련 데이터셋에 사용하며 모델 훈련이 진행될 것임을 알림.이때 드롭아웃(dropout)이 활성화됨.
* model.eval(): 모델을 평가할 때는 모든 노드를 사용하겠다는 의미로 검증과 테스트 데이터셋에 사용합.